### ISSUE TITLE
Questions about  Quadratic transform method for fractional programming

### ISSUE THREAD

**Issue by hahahadhy** [whalewang410/Energy-Efficient_UAV_Communication_With_Trajectory_Optimization#1]
I have not found any theoretical references to the method you are using, could you please tell me the references of the algorithm you are using, I would like to look it up. Looking forward to your reply.

**Comment by whalewang410** [comment]
Thanks for the interest in my coding. The method is in the artical "Fractional Programming for Communication Systems—Part I: Power Control and Beamforming". By the way, when you learn the method, you should notice the apply condition of the method.
